# posts/2025-07-05-0900-beach-vibes/meta.yml
caption: |
  Catching sunrise ☀️🌊
  #ExtraEdge #BeachLife
platforms: [instagram, twitter]   # one, the other, or both
datetime: 2025-07-05 09:00        # local Jamaica time
status: pending                   # action flips to "posted"

